// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sysconf.proto

package org.brewchain.sdk.model;

public final class Sysconf {
  private Sysconf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DomainsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.chain.sdk.model.Domains)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string domian = 1;</code>
     */
    java.util.List<java.lang.String>
        getDomianList();
    /**
     * <code>repeated string domian = 1;</code>
     */
    int getDomianCount();
    /**
     * <code>repeated string domian = 1;</code>
     */
    java.lang.String getDomian(int index);
    /**
     * <code>repeated string domian = 1;</code>
     */
    com.google.protobuf.ByteString
        getDomianBytes(int index);
  }
  /**
   * Protobuf type {@code com.chain.sdk.model.Domains}
   */
  public  static final class Domains extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.chain.sdk.model.Domains)
      DomainsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Domains.newBuilder() to construct.
    private Domains(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Domains() {
      domian_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Domains(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                domian_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              domian_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          domian_ = domian_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sysconf.internal_static_com_chain_sdk_model_Domains_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sysconf.internal_static_com_chain_sdk_model_Domains_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Sysconf.Domains.class, Sysconf.Domains.Builder.class);
    }

    public static final int DOMIAN_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList domian_;
    /**
     * <code>repeated string domian = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDomianList() {
      return domian_;
    }
    /**
     * <code>repeated string domian = 1;</code>
     */
    public int getDomianCount() {
      return domian_.size();
    }
    /**
     * <code>repeated string domian = 1;</code>
     */
    public java.lang.String getDomian(int index) {
      return domian_.get(index);
    }
    /**
     * <code>repeated string domian = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDomianBytes(int index) {
      return domian_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < domian_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, domian_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < domian_.size(); i++) {
          dataSize += computeStringSizeNoTag(domian_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDomianList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Sysconf.Domains)) {
        return super.equals(obj);
      }
      Sysconf.Domains other = (Sysconf.Domains) obj;

      boolean result = true;
      result = result && getDomianList()
          .equals(other.getDomianList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDomianCount() > 0) {
        hash = (37 * hash) + DOMIAN_FIELD_NUMBER;
        hash = (53 * hash) + getDomianList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Sysconf.Domains parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sysconf.Domains parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sysconf.Domains parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sysconf.Domains parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sysconf.Domains parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sysconf.Domains parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sysconf.Domains parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Sysconf.Domains parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Sysconf.Domains parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Sysconf.Domains parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Sysconf.Domains parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Sysconf.Domains parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Sysconf.Domains prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.chain.sdk.model.Domains}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.chain.sdk.model.Domains)
        Sysconf.DomainsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Sysconf.internal_static_com_chain_sdk_model_Domains_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Sysconf.internal_static_com_chain_sdk_model_Domains_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Sysconf.Domains.class, Sysconf.Domains.Builder.class);
      }

      // Construct using com.chain.sdk.model.Sysconf.Domains.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        domian_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Sysconf.internal_static_com_chain_sdk_model_Domains_descriptor;
      }

      @java.lang.Override
      public Sysconf.Domains getDefaultInstanceForType() {
        return Sysconf.Domains.getDefaultInstance();
      }

      @java.lang.Override
      public Sysconf.Domains build() {
        Sysconf.Domains result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Sysconf.Domains buildPartial() {
        Sysconf.Domains result = new Sysconf.Domains(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          domian_ = domian_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.domian_ = domian_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Sysconf.Domains) {
          return mergeFrom((Sysconf.Domains)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Sysconf.Domains other) {
        if (other == Sysconf.Domains.getDefaultInstance()) return this;
        if (!other.domian_.isEmpty()) {
          if (domian_.isEmpty()) {
            domian_ = other.domian_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDomianIsMutable();
            domian_.addAll(other.domian_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Sysconf.Domains parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Sysconf.Domains) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList domian_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDomianIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          domian_ = new com.google.protobuf.LazyStringArrayList(domian_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string domian = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDomianList() {
        return domian_.getUnmodifiableView();
      }
      /**
       * <code>repeated string domian = 1;</code>
       */
      public int getDomianCount() {
        return domian_.size();
      }
      /**
       * <code>repeated string domian = 1;</code>
       */
      public java.lang.String getDomian(int index) {
        return domian_.get(index);
      }
      /**
       * <code>repeated string domian = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDomianBytes(int index) {
        return domian_.getByteString(index);
      }
      /**
       * <code>repeated string domian = 1;</code>
       */
      public Builder setDomian(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDomianIsMutable();
        domian_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string domian = 1;</code>
       */
      public Builder addDomian(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDomianIsMutable();
        domian_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string domian = 1;</code>
       */
      public Builder addAllDomian(
          java.lang.Iterable<java.lang.String> values) {
        ensureDomianIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, domian_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string domian = 1;</code>
       */
      public Builder clearDomian() {
        domian_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string domian = 1;</code>
       */
      public Builder addDomianBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDomianIsMutable();
        domian_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.chain.sdk.model.Domains)
    }

    // @@protoc_insertion_point(class_scope:com.chain.sdk.model.Domains)
    private static final Sysconf.Domains DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Sysconf.Domains();
    }

    public static Sysconf.Domains getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Domains>
        PARSER = new com.google.protobuf.AbstractParser<Domains>() {
      @java.lang.Override
      public Domains parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Domains(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Domains> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Domains> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Sysconf.Domains getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chain_sdk_model_Domains_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chain_sdk_model_Domains_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsysconf.proto\022\023com.chain.sdk.model\"\031\n\007" +
      "Domains\022\016\n\006domian\030\001 \003(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_chain_sdk_model_Domains_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chain_sdk_model_Domains_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chain_sdk_model_Domains_descriptor,
        new java.lang.String[] { "Domian", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
